### ISSUE TITLE
Can't pin Teamspeak into taskbar only icon widget

### ISSUE THREAD

**Issue by toni0491** [flathub/com.teamspeak.TeamSpeak#1]
On Fedora 29 KDE Plasma. I try to pin the Teamspeak application to the task bar but pin option it's gray color and I can't click.

**Comment by Zlopez** [comment]
Could you send a picture? Just to be clear, what exactly the issue looks.

**Comment by toni0491** [comment]
![screenshot_20190126_143143](https://user-images.githubusercontent.com/25155384/51787877-5d33a000-2177-11e9-95cd-192b73510f29.png)
Fijar=Pin
I can pin all other flatpak apps

**Comment by Zlopez** [comment]
What other flatpak do you have? I will look at the permissions and compare them.

**Comment by Zlopez** [comment]
I found out this issue is the result of executing application by script. You will have the same issue, if you try to use the TeamSpeak installed by the .run script from official site.
I will try to report this issue on the KDE bugtracker.

**Comment by Zlopez** [comment]
Link to the bug in KDE bugtracker - https://bugs.kde.org/show_bug.cgi?id=403666

**Comment by Zlopez** [comment]
I recently switched to KDE (Fedora 35 Kinoite) as my OS for desktop and found out how you can pin the flathub TeamSpeak to task bar.

This is what you need to do:
1) Open up the Application->Launcher
2) Search for TeamSpeak
3) Right click on the TeamSpeak entry
4) Pin to taskbar

There is just one issue, that when you click on the icon in taskbar, it will open the script and you will see another icon beside it.
![Screenshot_20220106_210301](https://user-images.githubusercontent.com/6943409/148444125-aa304d50-8dd8-4e12-9805-6d3e66d5b530.png)
