### ISSUE TITLE
Unable to switch to beta branch

### ISSUE THREAD

**Issue by svelle** [flathub/com.teamspeak.TeamSpeak#15]
I've been using the app for quite a long time and it's working mostly flawless for me.

However I recently wanted to switch to the beta branch to use some of the sweet new features (Automatic voice leveling!!!!) and am getting greeted with permissions issues by the auto updater of teamspeak.

Just wanted to check in and see if this is something that can be fixed in this package or if I should just switch to the version from teamspeak.com for now until the changes are merged into the stable branch.

Thanks for your hard work folks and keep it up!

**Comment by Zlopez** [comment]
The auto updater shouldn't be used for the flathub version, the updates should be done using flatpak. And I don't have beta branch for the teamspeak.

**Comment by svelle** [comment]
I know, I don't use it for updating the app. 
Unfortunately it seems like this is the only way to get the beta releases from teamspeak. I checked their website and there only seems to be downloads for the stable releases :/ 
![teamspeak](https://user-images.githubusercontent.com/7526550/76853644-fcb96380-684d-11ea-8d61-6ca05012a88e.png)

**Comment by Zlopez** [comment]
Unfortunately, I can't do anything with it then :-(

**Comment by svelle** [comment]
No problem. Thanks for looking into this and providing the package :)
