### ISSUE TITLE
I can't type in Japanese.

### ISSUE THREAD

**Issue by Zel9278** [flathub/com.teamspeak.TeamSpeak#22]
I put in teamspeak with flatpak, but I can't enter Japanese.
What I've tried is the information already lying around on the net, but it's all gone.
The inputs I'm using are ibus and ibus-mozc.

**Comment by Zlopez** [comment]
Could you try if you have the same issue with non flatpak version of TeamSpeak?

**Comment by Zel9278** [comment]
> Could you try if you have the same issue with non flatpak version of TeamSpeak?

not work...

**Comment by Zlopez** [comment]
@Zel9278 If this is not working in the non flatpak version of TeamSpeak either, you should report the issue on the official channel, in the case of TeamSpeak.

**Comment by Zlopez** [comment]
Closing this, because it's an upstream issue.
