### ISSUE TITLE
Process not exiting

### ISSUE THREAD

**Issue by lukashass** [flathub/com.teamspeak.TeamSpeak#27]
After closing the teamspeak window one process `ts3client_linux_amd64` keeps running and takes 100% CPU on one core.

**Comment by Zlopez** [comment]
I tried it on my machine with Fedora 34 Silverblue running GNOME 40 and couldn't reproduce the issue. The process ends up together with window.

Could you try standard TeamSpeak client, to see if the issue persist?

**Comment by Zlopez** [comment]
Closing, because there was no response from reporter for 9 months.
