### ISSUE TITLE
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first

### ISSUE THREAD

**Issue by peterge1998** [flathub/com.teamspeak.TeamSpeak#29]
### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

1. flatpak install flathub com.teamspeak.TeamSpeak
2. flatpak update
3. flatpak run com.teamspeak.TeamSpeak

### Expected Behavior

Open Teamspeak3

### Actual Behavior

➜  ~ flatpak run com.teamspeak.TeamSpeak           
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
Qt: Session management error: None of the authentication protocols specified are supported

**Comment by Zlopez** [comment]
I tried to run the flatpak on my machine and the issue is really there, but the TeamSpeak starts anyway.

**Comment by Zlopez** [comment]
I would recommend looking at the [official forum](https://community.teamspeak.com/c/suggestions-and-feedback/TS3-feedback/13) and see if somebody doesn't have similar issue.

**Comment by Zlopez** [comment]
Maybe some update that was applied during reboot.

**Comment by peterge1998** [comment]
The error is happening again...
