### ISSUE TITLE
Pop!_OS 22.04 no sound input or output

### ISSUE THREAD

**Issue by WalnussPower** [flathub/com.teamspeak.TeamSpeak#34]
I'm trying to use this on Pop!_OS 22.04, but Teamspeak does not output any sound. Also, recording does not work either, it seems.
I use Pipewire. Could that be the reason?

**Comment by Zlopez** [comment]
There should be update soon, try it and see if the issue remains.

**Comment by WalnussPower** [comment]
Thanks for the quick response. Turns out, I had to explicitly change the Capture Mode to ALSA rather than have it be determined automatically.

**Comment by Zlopez** [comment]
At least I updated the runtime to newer one :-)

I'm closing this issue, feel free to open it, if you don't think it's resolved.
