### ISSUE TITLE
TeamSpeak 5

### ISSUE THREAD

**Issue by brndd** [flathub/com.teamspeak.TeamSpeak#47]
Please consider updating this package to TeamSpeak 5, or providing an alternative package for it. It seems development on TS3 has basically ceased, and many Linux issues on it have gone unfixed for years. For example on Wayland it's impossible to bind any keyboard shortcuts whatsoever -- only mouse buttons work -- even when the window is in focus (so it is not the usual Wayland global shortcuts issue).

TS5, in comparison, does not have these issues in my experience. With KDE's legacy global shortcut support it even works alright on Wayland.

**Comment by Zlopez** [comment]
As I'm not using the TeamSpeak anymore for some time I wasn't aware there is TeamSpeak 5. The issue with TeamSpeak 4 is that there wasn't anything to package as they didn't provide official Linux client, at least the last time I checked. Let's see how the situation looks now.

**Comment by Zlopez** [comment]
From what I see the TeamSpeak 5 is still in beta. If I will package it will probably stay in beta branch at least till it will be officially released.

**Comment by brndd** [comment]
There is an official client, but it is still in beta. That said, they seem to consider it stable enough that the Download link on their home page takes you to TS5 before TS3.

I already packaged it into Flatpak myself for a test, and so far it seems to work alright -- but I figured I would ask you if you're interested in packaging it before looking into Flathub submissions myself. My work is at https://github.com/brndd/com.teamspeak.TeamSpeak5 -- feel free to use it.

**Comment by brndd** [comment]
I should add that they seem to have been a bit more considerate of Linux with TS5. The client now uses XDG basedirs correctly, for example. Sadly it seems they have not yet implemented any Wayland hotkey APIs, but there are workarounds for this.

**Comment by Zlopez** [comment]
I will look into it, but if you want, you can create a PR directly to this repository.

**Comment by Zlopez** [comment]
TeamSpeak 5 is now in beta branch. I added README to beta branch with instructions, but I'm not sure how long it takes for flatpak to be available in `flathub-beta` remote.

If the flatpak will be stable enough, I will probably move it to stable branch.

**Comment by Bixilon** [comment]
@Zlopez Why was this done? I am absolutely no fan of teamspeak 5. Can you consider creating a new repository/app for TeamSpeak5?

**Comment by Zlopez** [comment]
It would be better to create one for TeamSpeak3 as the 5 is recommended on https://teamspeak.com/.
