### ISSUE TITLE
package overwrites TS3 clients as well

### ISSUE THREAD

**Issue by quoten3m0** [flathub/com.teamspeak.TeamSpeak#56]
I assume this is a mistake, but the update overwrites all TS versions that have been installed before. No matter whether it has been a TS5 or TS3 client before.

Because TS5 needs an TS account as mandatory, it's no longer possible to use TS without an account, which is supported by TS itself via TS3. TS3 is also still a stable version available at the TS site:
[
https://www.teamspeak.com/de/downloads/#ts3client](url)

I would therefore recommend to split it into two versions, one TS3 and TS5.

TS5 is NOT simply and update of TS3, and therefore overwriting it is simply wrong in my opinion.

**Comment by LeonMarcel-HD** [comment]
@Zlopez decided it would be a good idea to forcely overwrite the installation https://github.com/flathub/com.teamspeak.TeamSpeak/issues/52#issuecomment-1886759492

Plot twist it is not

**Comment by Zlopez** [comment]
There is already a work being done on [TS3 version for flathub](https://github.com/flathub/flathub/pull/4851). It will be a separate application as requested, this repository will stay as TS5. I'm sorry this caused so many issues.

**Comment by LeonMarcel-HD** [comment]
The requested version should become TS5 and this one should stay on TS3...

**Comment by Zlopez** [comment]
I think `com.teamspeak.TeamSpeak` should always be the latest and the older one should be `com.teamspeak.TeamSpeak3` flathub namespace. But it was my fault to start with TeamSpeak3 and using `com.teamspeak.TeamSpeak` namespace.

**Comment by nmlynch94** [comment]
I would maybe agree with you if teamspeak5 weren't clearly labeled as a beta client. This turns the package that provided the latest stable client into a package for beta-testers. Too late to do anything now since the other package was accepted, and I appreciate the work you do to maintain this package, but this decision to supposedly make the namespace more clear has just caused extra work for users and made it less clear in my opinion.

**Comment by Zlopez** [comment]
@nmlynch94 I don't disagree with you, but it was the same way when this was TeamSpeak 3 only. People expected TeamSpeak 5 as this is what they get from official site when just following the links for download. And it seems more reasonable to make the com.teamspeak.TeamSpeak the one that is officially available than creating another com.teamspeak.TeamSpeak5 for TS5 only.

I just didn't expected so many people complaining about the change as nobody from those people said anything when the discussion about TS5 happened. I had it in beta branch for some time and just got complains that it's not the default one. As they say you never make everyone happy.
