### ISSUE TITLE
How to install addons and themes?

### ISSUE THREAD

**Issue by iamalsonothere** [flathub/com.teamspeak.TeamSpeak#57]

**Comment by Zlopez** [comment]
Does the default way not working for you? For example https://community.teamspeak.com/t/skin-colorful-teamspeak-a-teamspeak-5-extension/24082

**Comment by iamalsonothere** [comment]
No, the plugins section is settings is always empty for me

**Comment by Zlopez** [comment]
Could you check if the plugin is available in the folder mentioned in the link I shared? It's possible that the flatpak just doesn't have access to the folder.

**Comment by iamalsonothere** [comment]
Yes, the file is available and it does have permissions

**Comment by Zlopez** [comment]
I created a PR that should fix this issue. Could you try it?

You can do it by running this in terminal
```
flatpak install --user https://dl.flathub.org/build-repo/100362/com.teamspeak.TeamSpeak.flatpakref
flatpak run --user com.teamspeak.TeamSpeak
```

**Comment by Zlopez** [comment]
It seems that adding the `.config/TeamSpeak` folder didn't help as the default still points to `.var/app/com.teamspeak/TeamSpeak/.config`

So I need to find a way for TeamSpeak to use config folder from home instead of creating it's own.

**Comment by Zlopez** [comment]
Tested it with `--filesystem=xgd-config/TeamSpeak` and it worked as it should. #60 will fix the issue.

**Comment by Zlopez** [comment]
The default location for TeamSpeak 5 addons and themes is now working. Tested with https://community.teamspeak.com/t/skin-colorful-teamspeak-a-teamspeak-5-extension/24082
