### ISSUE TITLE
How do I enable the tray icon?

### ISSUE THREAD

**Issue by ghost** [flathub/com.teamspeak.TeamSpeak#6]
If I enable it in the design options it still doesn't display.

**Comment by Zlopez** [comment]
Hi, I tried it on GNOME 3 with TopIcons Plus and it's working.

What Desktop Environment are you using?

**Comment by vargbeaumont** [comment]
@Zlopez I am using GNOME 3.32 on Ubuntu 19.04 with the Ubuntu appindicators extension enabled.

**Comment by Zlopez** [comment]
I have the same version of GNOME, so it looks like the issue is in appindicators extension. Could you try it with TopIcons Plus, so we are sure?

**Comment by Zlopez** [comment]
I'm closing this because of the inactivity, feel free to open it again if issue persist.
